version: '3.1'

volumes:
  images:
  cache:

services:
  node:
    image: rdfriedl/sharp-image-server:latest
    ports:
    - 80:3000
    volumes:
    - cache:/cache
    - images:/images
    environment:
    - NODE_ENV=production
    deploy:
      replicas: 2
